### ISSUE TITLE
dyld`dyld_fatal_error

### ISSUE THREAD

**Issue by pqant** [fdzsergio/SFFocusViewLayout#3]
Hi , 

When we want to run sample application with XCode 7.2 then we're facing this error.It works charm on simulator but we couldn't find a way to run same code on a real device. ( IPhone 6 , IOS 9.x )

You can see the error through this link : http://snag.gy/XLjch.jpg

Do you have an idea ? 

Thanks

**Comment by m8282823** [comment]
same to me

**Comment by fdzsergio** [comment]
thanks for open an issue, I've fixed this issue in last commit

:surfer:

**Comment by pqant** [comment]
Thank you my friend , I'll try it asap.

**Comment by JHPG** [comment]
Hi,

I'm having the same error and my files are updated.

Do you have an idea ?
Thanks

**Comment by fdzsergio** [comment]
thanks! i've updated the example with new swift 2.2

**Comment by JHPG** [comment]
I updated the files and tried it again, but still with the same error.  :/
It happens only when I build on device.

**Comment by tosslife** [comment]
same too

dyld: Symbol not found: __TMPdCSs23_ContiguousArrayStorage
  Referenced from: /private/var/containers/Bundle/Application/C70EDF2D-01A9-477A-8147-20A61640E8F3/Example.app/Frameworks/SFFocusViewLayout.framework/SFFocusViewLayout
  Expected in: /private/var/containers/Bundle/Application/C70EDF2D-01A9-477A-8147-20A61640E8F3/Example.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/C70EDF2D-01A9-477A-8147-20A61640E8F3/Example.app/Frameworks/SFFocusViewLayout.framework/SFFocusViewLayout
(lldb)
