### ISSUE TITLE
strange behavior when embedded in navigation-controller

### ISSUE THREAD

**Issue by AnotherCoolDude** [fdzsergio/SFFocusViewLayout#5]
Hey,

i am using a ViewController, which is embedded in a NavigationController. Inside of that ViewController, i have a CollectionView that uses the SFFocusViewLayout. When i scroll down at a offset of approximately -64 and release my finger, it stops for a short duration and then snaps back to 0 offset. Using a ViewController without a NavigationController solves the issue. I guess calculation goes wrong at some point, when the CollectionView is not at yPosition 0 within the ViewController?

**Comment by fdzsergio** [comment]
You would use `self.edgesForExtendedLayout = UIRectEdgeNone;` to handle navigation bar offset.
